<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginLogout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>802f3e2c-677a-4658-afed-8a73e4f47340</testSuiteGuid>
   <testCaseLink>
      <guid>3cdffb66-9bcd-4c92-a6d1-ae0d677a130e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c7c02eee-b1b4-43fa-940d-06671728b740</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/usersLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e53cf5a-9552-4d99-96cc-092d35c1851e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2f68987-cac2-462a-9b66-765cbf8c81fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c7c02eee-b1b4-43fa-940d-06671728b740</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c9d197ce-0336-49a6-96e3-7439d8c02e23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c7c02eee-b1b4-43fa-940d-06671728b740</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e120ca52-a952-45e9-bcda-b310919f9b05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51151161-13a4-45c9-adf5-fa663c8802a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de0c68d6-d520-4d80-b803-eee299a355f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cfd9314-7c55-4f19-91a4-934edcdfaa5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fef844e7-9851-47bc-8316-93ebfbada12b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC_Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aac62bb7-cd1a-4a14-a2f6-f764ff9c9428</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22507ac3-c3bf-49bb-a3b7-875043fbc01d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb6a8574-8de2-44d1-a8c3-631d41c939cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b677660a-d254-4665-b7e1-2181072b4ec6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
