<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UpdateUser</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4362db9b-db2f-47d6-a4cc-2371f10e97fd</testSuiteGuid>
   <testCaseLink>
      <guid>0a66420c-1bca-4214-bd00-fac122c7c304</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UpdateUser/TC_UpdateUser</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c235c230-9f23-4a7e-999a-7bc199c70c8a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/userInfo</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b823466-8ebe-4442-92df-c0a993e63872</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ecb14cc-57e9-4a70-a381-c281da572b72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5337afc-46f1-4ddd-9e74-8b4dd6a7727c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96ecdf6a-922c-45d2-8a86-4be9c13f4d65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>723c4426-2a59-480b-ab05-1917dd7e9d53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27510a98-eb74-4b20-907f-9fe933865412</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15a13292-b199-44e6-807a-110c8fe644ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c235c230-9f23-4a7e-999a-7bc199c70c8a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>0a6bcf18-110d-4835-9917-0fb1c2e092db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c235c230-9f23-4a7e-999a-7bc199c70c8a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>ed2b0df8-ef6c-4e3e-ad47-a6e4ada07150</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c235c230-9f23-4a7e-999a-7bc199c70c8a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>telephone</value>
         <variableId>7579f919-37f3-4888-8bbc-0a76a98c88a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6a646bd-487c-439f-9f1c-a7eb6a43491a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3151b205-0eef-4dfb-8ec5-f1144bf9eecc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
