<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8c96a900-a2aa-4df5-9f0c-ac8a3d94fb28</testSuiteGuid>
   <testCaseLink>
      <guid>d0752570-6312-4d53-95e4-a4f2f3a3cdbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC_Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>df56fb3e-6222-4435-bc51-b05b0b72f8a7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/signUp</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e53cf5a-9552-4d99-96cc-092d35c1851e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2f68987-cac2-462a-9b66-765cbf8c81fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>df56fb3e-6222-4435-bc51-b05b0b72f8a7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>c9d197ce-0336-49a6-96e3-7439d8c02e23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>df56fb3e-6222-4435-bc51-b05b0b72f8a7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e120ca52-a952-45e9-bcda-b310919f9b05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51151161-13a4-45c9-adf5-fa663c8802a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de0c68d6-d520-4d80-b803-eee299a355f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cfd9314-7c55-4f19-91a4-934edcdfaa5c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
