<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SignUp</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>741b54df-db40-495b-b661-e8793a4148ac</testSuiteGuid>
   <testCaseLink>
      <guid>a75bcb5e-e044-49e1-9ee5-0cdc3e9523c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUp/TC_SignUp</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>14a72654-ae72-4fad-8f1e-a39fc6a2274f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/signUp</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0e2fc7b-8bf4-45c4-878a-6dc54f868416</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52ee3bdc-125f-4cef-a905-853fc86fc3e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef9aeb4e-221d-4223-b29c-d91d9002b097</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>14a72654-ae72-4fad-8f1e-a39fc6a2274f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>firstName</value>
         <variableId>cac10b80-1548-4d25-8d20-5ad9f7289279</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5afabb7-f05a-435e-8edf-e787873b8b9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>14a72654-ae72-4fad-8f1e-a39fc6a2274f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lastName</value>
         <variableId>85841b4d-197e-4daf-9975-3b652fe24e67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c0c1959-f365-4b94-b2e2-9211656963f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>14a72654-ae72-4fad-8f1e-a39fc6a2274f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>d106dcf1-7332-4d93-80de-3e7bbdf13e65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7e0e25b-010f-48e0-a768-064d43bf7c8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>14a72654-ae72-4fad-8f1e-a39fc6a2274f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>telephone</value>
         <variableId>9b98a574-fc9b-4e25-a67a-3c45ee364c68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa33a22f-2720-4afc-bb21-131102e9d0cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>14a72654-ae72-4fad-8f1e-a39fc6a2274f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>fd6e69fa-17d5-404d-a8f2-bacea04fbca6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78bb9f84-0596-4168-873d-8407fcb3810f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>14a72654-ae72-4fad-8f1e-a39fc6a2274f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>confirmPassword</value>
         <variableId>481d007c-ded9-42cd-804e-eba4fb8ca3c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c038dc82-f044-47d5-ba98-4ae65744d79a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42e5f20f-1d91-4087-b7ac-debc9ac692b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f009c43-f47a-463f-a41e-e905d7037857</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5131532b-ebd9-4fd1-aa8a-f17c13e67037</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2c643ff-04e4-4504-9c61-5058e5a37d0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC_Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aac62bb7-cd1a-4a14-a2f6-f764ff9c9428</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22507ac3-c3bf-49bb-a3b7-875043fbc01d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb6a8574-8de2-44d1-a8c3-631d41c939cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b677660a-d254-4665-b7e1-2181072b4ec6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
